name: FastAPI - Basic Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  fastapi-tests-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: 🔄 Checkout do código
        uses: actions/checkout@v4

      - name: 🐍 Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: 🛠️ Instalar Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: 📦 Instalar dependências com Poetry
        run: poetry install --no-interaction --no-root

      - name: 🧪 Rodar testes
        run: poetry run pytest -v

      - name: 🐳 Build da imagem Docker
        run: docker build -t fastapi-app:latest .

      - name: 🚀 Testar execução do container
        run: docker run -d -p 8080:8080 fastapi-app:latest